In [0]:
import numpy as np
import pandas as pd
import seaborn as sb
sb.set_style("dark")
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.decomposition import PCA
from sklearn.svm import SVC
from lightgbm import LGBMClassifier
import xgboost as xgb
from sklearn import tree
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [0]:
from sklearn.model_selection import StratifiedKFold
def Stacking(model,train,y,test,n_fold):
  folds=StratifiedKFold(n_splits=n_fold,random_state=1)
  #test_pred=np.empty((test.shape[0],1),float)
  train_pred=np.empty((0,1),float)
  test_pred=np.empty((0,1),float)
  for train_indices,val_indices in folds.split(train,y.values):
    x_train,x_val=train.iloc[train_indices],train.iloc[val_indices]
    y_train,y_val=y.iloc[train_indices],y.iloc[val_indices]
    
    model.fit(X=x_train,y=y_train)
    train_pred=np.append(train_pred,model.predict(x_val))
  test_pred=np.append(test_pred,model.predict(test))
  return test_pred.reshape(-1,1),train_pred

# ***PCA with 50 components(96.07% highest)*** 

In [0]:
train_data = pd.read_csv("train.csv")[:-2] #reading the csv files using pandas
test_data = pd.read_csv("test.csv")[:-2]

In [0]:
y = train_data['label']

## Dropping the variable 'label' from X variable 
X = train_data.drop(columns = 'label')

## Printing the size of data 
print(train_data.shape)
print(X)
print(y)

(41998, 785)
       pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0           0       0       0       0  ...         0         0         0         0
1           0       0       0       0  ...         0         0         0         0
2           0       0       0       0  ...         0         0         0         0
3           0       0       0       0  ...         0         0         0         0
4           0       0       0       0  ...         0         0         0         0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
41993       0       0       0       0  ...         0         0         0         0
41994       0       0       0       0  ...         0         0         0         0
41995       0       0       0       0  ...         0         0         0         0
41996       0       0       0       0  ...         0         0         0         0
41997       0       0       0       0  ...         0         0         0  

In [0]:
## Normalization

X = X/255.0
test_data = test_data/255.0

print("X:", X.shape)
print("test_data:", test_data.shape)

X: (41998, 784)
test_data: (27998, 784)


In [0]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)

In [0]:
pca = PCA(n_components=50)
pca.fit(X_train)
transform_train = pca.transform(X_train)
transform_test = pca.transform(X_test)

In [0]:
transform_train = pd.DataFrame(transform_train)
transform_test = pd.DataFrame(transform_test)

In [0]:
#Setup a knn classifier with k neighbors
model1_a = KNeighborsClassifier(n_neighbors=6,weights='distance')
model1_a.fit(transform_train,y_train)
pred1_a=model1_a.predict(transform_test)
train_pred1_a=model1_a.predict(transform_train)
print(model1_a.score(transform_test,y_test))

0.9592857142857143


In [0]:
#Setup a knn classifier with k neighbors
model1_b = KNeighborsClassifier(n_neighbors=6,p=2,algorithm='brute')
model1_b.fit(transform_train,y_train)
pred1_b=model1_b.predict(transform_test)
train_pred1_b=model1_b.predict(transform_train)
print(model1_b.score(transform_test,y_test))

0.9550793650793651


In [0]:
model1_c = SVC(kernel="rbf",C=1, gamma=0.01)
model1_c.fit(transform_train,y_train)
pred1_c=model1_c.predict(transform_test)
train_pred1_c=model1_c.predict(transform_train)
model1_c.score(transform_test,y_test)

0.957936507936508

In [0]:
model1_d =SVC(kernel="poly",C=5, gamma=0.01)
model1_d.fit(transform_train,y_train)
pred1_d=model1_d.predict(transform_test)
train_pred1_d=model1_d.predict(transform_train)
model1_d.score(transform_test,y_test)

0.9607142857142857

In [0]:
model1_e = LGBMClassifier( random_state=5,n_estimators=250)
model1_e.fit(transform_train,y_train)
pred1_e=model1_e.predict(transform_test)
train_pred1_e=model1_e.predict(transform_train)
model1_e.score(transform_test,y_test)

0.9465079365079365

In [0]:
model1_f = LGBMClassifier( random_state=5,learning_rate=0.5,max_depth=5)
model1_f.fit(transform_train,y_train)
pred1_f=model1_f.predict(transform_test)
train_pred1_f=model1_f.predict(transform_train)
model1_f.score(transform_test,y_test)

0.9471428571428572

In [0]:
model1_g = xgb.XGBClassifier(random_state=1,learning_rate=0.5,n_estimators=250)
model1_g.fit(transform_train,y_train)
pred1_g=model1_g.predict(transform_test)
train_pred1_g=model1_g.predict(transform_train)
model1_g.score(transform_test,y_test)

0.9430952380952381

In [0]:
model1_h = RandomForestClassifier(n_estimators=300)
model1_h.fit(transform_train,y_train)
pred1_h=model1_h.predict(transform_test)
train_pred1_h=model1_h.predict(transform_train)
model1_h.score(transform_test,y_test)

0.9318253968253968

# **PCA with 100 feaures(96.3% highest)**

In [0]:
train_data = pd.read_csv("train.csv")[:-2] #reading the csv files using pandas
test_data = pd.read_csv("test.csv")[:-2]

In [0]:
y = train_data['label']

## Dropping the variable 'label' from X variable 
X = train_data.drop(columns = 'label')

## Printing the size of data 
print(train_data.shape)
print(X)
print(y)

(41998, 785)
       pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0           0       0       0       0  ...         0         0         0         0
1           0       0       0       0  ...         0         0         0         0
2           0       0       0       0  ...         0         0         0         0
3           0       0       0       0  ...         0         0         0         0
4           0       0       0       0  ...         0         0         0         0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
41993       0       0       0       0  ...         0         0         0         0
41994       0       0       0       0  ...         0         0         0         0
41995       0       0       0       0  ...         0         0         0         0
41996       0       0       0       0  ...         0         0         0         0
41997       0       0       0       0  ...         0         0         0  

In [0]:
## Normalization

X = X/255.0
test_data = test_data/255.0

print("X:", X.shape)
print("test_data:", test_data.shape)

X: (41998, 784)
test_data: (27998, 784)


In [0]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)


In [0]:
pca = PCA(n_components=100)
pca.fit(X_train)
transform_train = pca.transform(X_train)
transform_test = pca.transform(X_test)

In [0]:
transform_train = pd.DataFrame(transform_train)
transform_test = pd.DataFrame(transform_test)

In [0]:
#Setup a knn classifier with k neighbors
model2_a = KNeighborsClassifier(n_neighbors=6,weights='distance')
model2_a.fit(transform_train,y_train)
pred2_a=model2_a.predict(transform_test)
train_pred2_a=model2_a.predict(transform_train)
print(model2_a.score(transform_test,y_test))

0.9554761904761905


In [0]:
#Setup a knn classifier with k neighbors
model2_b = KNeighborsClassifier(n_neighbors=6,p=2,algorithm='brute')
model2_b.fit(transform_train,y_train)
pred2_b=model2_b.predict(transform_test)
train_pred2_b=model2_b.predict(transform_train)
print(model2_b.score(transform_test,y_test))

0.9496825396825397


In [0]:
model2_c = SVC(kernel="rbf",C=1, gamma=0.01)
model2_c.fit(transform_train,y_train)
pred2_c=model2_c.predict(transform_test)
train_pred2_c=model2_c.predict(transform_train)
model2_c.score(transform_test,y_test)

0.959047619047619

In [0]:
model2_d =SVC(kernel="poly",C=5, gamma=0.01,class_weight='balanced',degree=3,)
model2_d.fit(transform_train,y_train)
pred2_d=model2_d.predict(transform_test)
train_pred2_d=model2_d.predict(transform_train)
model2_d.score(transform_test,y_test)

0.9636507936507936

In [0]:
model2_e = LGBMClassifier( random_state=5,n_estimators=250)
model2_e.fit(transform_train,y_train)
pred2_e=model2_e.predict(transform_test)
train_pred2_e=model2_e.predict(transform_train)
model2_e.score(transform_test,y_test)

0.9452380952380952

In [0]:
model2_f = LGBMClassifier( random_state=5,learning_rate=0.5,max_depth=5)
model2_f.fit(transform_train,y_train)
pred2_f=model2_f.predict(transform_test)
train_pred2_f=model2_f.predict(transform_train)
model2_f.score(transform_test,y_test)

0.9426190476190476

In [0]:
model2_g = xgb.XGBClassifier(random_state=1,learning_rate=0.5,n_estimators=250)
model2_g.fit(transform_train,y_train)
pred2_g=model2_g.predict(transform_test)
train_pred2_g=model2_g.predict(transform_train)
model2_g.score(transform_test,y_test)

0.9396825396825397

In [0]:
model2_h = RandomForestClassifier(n_estimators=300)
model2_h.fit(transform_train,y_train)
pred2_h=model2_h.predict(transform_test)
train_pred2_h=model2_h.predict(transform_train)
model2_h.score(transform_test,y_test)

0.9302380952380952

In [0]:
print(pred1_a)
print(pred1_b)
print(pred1_c)
print(pred1_d)
print(pred1_e)
print(pred1_f)
print(pred1_g)
print(pred1_h)
print(pred2_a)
print(pred2_b)
print(pred2_c)
print(pred2_d)
print(pred2_e)
print(pred2_f)
print(pred2_g)
print(pred2_h)

[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]


# **On Entire dataset(96.26% highest)**

In [0]:
train_data = pd.read_csv("train.csv")[:-2] #reading the csv files using pandas
test_data = pd.read_csv("test.csv")[:-2]

In [0]:
## Separating the X and Y variable

y = train_data['label']

## Dropping the variable 'label' from X variable 
X = train_data.drop(columns = 'label')

## Printing the size of data 
print(train_data.shape)

(41998, 785)


In [0]:
## Normalization

X = X/255.0
test_data = test_data/255.0

print("X:", X.shape)
print("test_data:", test_data.shape)

X: (41998, 784)
test_data: (27998, 784)


In [0]:
# train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)

In [0]:
model3_a = KNeighborsClassifier(n_neighbors=5,weights='distance')
model3_a.fit(X_train,y_train)
pred3_a=model3_a.predict(X_test)
train_pred3_a=model3_a.predict(X_train)
model3_a.score(X_test,y_test)


0.9500793650793651

In [0]:
model3_b = SVC(kernel="rbf")
model3_b.fit(X_train,y_train)
pred3_b=model3_b.predict(X_test)
train_pred3_b=model3_b.predict(X_train)
model3_b.score(X_test,y_test)

0.9626984126984127

In [0]:
model3_c = SVC(kernel="poly",C=10, gamma=0.1)
model3_c.fit(X_train,y_train)
pred3_c=model3_c.predict(X_test)
train_pred3_c=model3_c.predict(X_train)
model3_c.score(X_test,y_test)


0.954920634920635

In [0]:
model3_d = RandomForestClassifier(n_estimators=500,)
model3_d.fit(X_train,y_train)
pred3_d=model3_d.predict(X_test)
train_pred3_d=model3_d.predict(X_train)
model3_d.score(X_test,y_test)

0.9531746031746032

In [0]:
model3_e = LGBMClassifier( random_state=5,n_estimators=300)
model3_e.fit(X_train,y_train)
pred3_e=model3_e.predict(X_test)
train_pred3_e=model3_e.predict(X_train)
model3_e.score(X_test,y_test)

0.960952380952381

In [0]:
model3_f = xgb.XGBClassifier(random_state=1,learning_rate=0.01,n_estimators=100,max_depth=5)
model3_f.fit(X_train,y_train)
pred3_f=model3_f.predict(X_test)
train_pred3_f=model3_f.predict(X_train)
model3_f.score(X_test,y_test)

0.8885714285714286

In [0]:
print(pred1_a)
print(pred1_b)
print(pred1_c)
print(pred1_d)
print(pred1_e)
print(pred1_f)
print(pred1_g)
print(pred1_h)
print(pred2_a)
print(pred2_b)
print(pred2_c)
print(pred2_d)
print(pred2_e)
print(pred2_f)
print(pred2_g)
print(pred2_h)
print(pred3_a)
print(pred3_b)
print(pred3_c)
print(pred3_d)
print(pred3_e)
print(pred3_f)

[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]
[0 8 0 ... 0 6 7]


# **Voting of above algo(96.66% highest)**

In [0]:
from statistics import mode
final_pred = np.array([])
for i in range(0,len(X_test)):
  try:
    final_pred = np.append(final_pred, mode([pred1_a[i], pred1_b[i], pred1_c[i], pred1_d[i],pred1_e[i],pred1_f[i],pred1_g[i],pred1_h[i],pred2_a[i], pred2_b[i], pred2_c[i], pred2_d[i],pred2_e[i],pred3_a[i], pred3_b[i], pred3_c[i], pred3_d[i],pred3_e[i]]))
  except:
    try:
      final_pred = np.append(final_pred, mode([ pred1_c[i], pred1_d[i], pred2_c[i], pred2_d[i], pred3_b[i],pred3_e[i]]))
    except:
      final_pred = np.append(final_pred,pred2_c[i])

    

In [0]:
# confusion matrix and accuracy

# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=final_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=final_pred))

accuracy: 0.9656349206349206 

[[1197    0    2    0    0    2   10    0    8    2]
 [   0 1353    4    4    4    1    2    2    2    0]
 [   2    8 1204    5    7    1    4    5   11    1]
 [   1    5   13 1272    0   21    0    9    6    3]
 [   2    6    3    1 1172    1    8    1    2   27]
 [   2    3    2   17    0 1102    8    0    5    3]
 [   5    1    2    0    1    7 1212    0    2    0]
 [   2   13    8    2    5    1    0 1321    1   21]
 [   1   11    4   15    3   14    5    1 1166    5]
 [   3    1    1   12   20    6    0   18    6 1168]]


In [0]:
from statistics import mode
final_pred = np.array([])
pred = np.array([])
for i in range(0,len(X_test)):
  try:
    final_pred = np.append(final_pred, mode([ pred1_b[i], pred1_c[i], pred1_d[i],pred2_a[i], pred2_b[i], pred2_c[i], pred2_d[i],pred2_e[i],pred3_a[i],pred3_e[i]]))
  except:
    try:
      final_pred = np.append(final_pred, mode([ pred1_c[i], pred1_d[i], pred2_c[i], pred2_d[i], ]))
    except:
      final_pred = np.append(final_pred,pred2_c[i])

# confusion matrix and accuracy

# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=final_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=final_pred))

accuracy: 0.9661111111111111 

[[1197    0    2    0    1    2    8    0    9    2]
 [   0 1354    4    3    4    1    1    3    2    0]
 [   2    9 1205    3    6    1    3    5   13    1]
 [   0    5   12 1270    0   21    0   10    7    5]
 [   1    5    2    1 1179    1    5    1    2   26]
 [   1    3    1   17    0 1105    8    0    4    3]
 [   6    1    1    0    1    8 1212    0    1    0]
 [   1   15    8    2    7    1    1 1316    1   22]
 [   1   14    2   12    3   15    4    1 1167    6]
 [   4    2    1   14   18    5    0   16    7 1168]]


# **Stacking Level 1(96.3% highest)**

# **On all**

In [0]:
pred1_a=pd.DataFrame(pred1_a)
pred1_b=pd.DataFrame(pred1_b)
pred1_c=pd.DataFrame(pred1_c)
pred1_d=pd.DataFrame(pred1_d)
pred1_e=pd.DataFrame(pred1_e)
pred1_f=pd.DataFrame(pred1_f)
pred1_g=pd.DataFrame(pred1_g)
pred1_h=pd.DataFrame(pred1_h)

pred2_a=pd.DataFrame(pred2_a)
pred2_b=pd.DataFrame(pred2_b)
pred2_c=pd.DataFrame(pred2_c)
pred2_d=pd.DataFrame(pred2_d)
pred2_e=pd.DataFrame(pred2_e)
pred2_f=pd.DataFrame(pred2_f)
pred2_g=pd.DataFrame(pred2_g)
pred2_h=pd.DataFrame(pred2_h)

pred3_a=pd.DataFrame(pred3_a)
pred3_b=pd.DataFrame(pred3_b)
pred3_c=pd.DataFrame(pred3_c)
pred3_d=pd.DataFrame(pred3_d)
pred3_e=pd.DataFrame(pred3_e)



In [0]:
df = pd.concat([pred1_a, pred1_b,pred1_c,pred1_d,pred1_e,pred1_f,pred1_g,pred2_a, pred2_b,pred2_c,pred2_d,pred2_e,pred2_f,pred2_g,pred3_a,pred3_b,pred3_c,pred3_d,pred3_e], axis=1)

In [0]:
df.head()

0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
1  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8  8
2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
3  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
4  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7  7

In [0]:
train_pred1_a=pd.DataFrame(train_pred1_a)
train_pred1_b=pd.DataFrame(train_pred1_b)
train_pred1_c=pd.DataFrame(train_pred1_c)
train_pred1_d=pd.DataFrame(train_pred1_d)
train_pred1_e=pd.DataFrame(train_pred1_e)
train_pred1_f=pd.DataFrame(train_pred1_f)
train_pred1_g=pd.DataFrame(train_pred1_g)
train_pred1_h=pd.DataFrame(train_pred1_h)

train_pred2_a=pd.DataFrame(train_pred2_a)
train_pred2_b=pd.DataFrame(train_pred2_b)
train_pred2_c=pd.DataFrame(train_pred2_c)
train_pred2_d=pd.DataFrame(train_pred2_d)
train_pred2_e=pd.DataFrame(train_pred2_e)
train_pred2_f=pd.DataFrame(train_pred2_f)
train_pred2_g=pd.DataFrame(train_pred2_g)
train_pred2_h=pd.DataFrame(train_pred2_h)

train_pred3_a=pd.DataFrame(train_pred3_a)
train_pred3_b=pd.DataFrame(train_pred3_b)
train_pred3_c=pd.DataFrame(train_pred3_c)
train_pred3_d=pd.DataFrame(train_pred3_d)
train_pred3_e=pd.DataFrame(train_pred3_e)

In [0]:
train_df = pd.concat([train_pred1_a, train_pred1_b,train_pred1_c,train_pred1_d,train_pred1_e,train_pred1_f,train_pred1_g,train_pred2_a, train_pred2_b,train_pred2_c,train_pred2_d,train_pred2_e,train_pred2_f,train_pred2_g,train_pred3_a,train_pred3_b,train_pred3_c,train_pred3_d,train_pred3_e], axis=1)

In [0]:
train_df.head()

0  0  0  0  0  0  0  0  0  0  0  0
0  5  5  5  5  5  5  5  5  5  5  5  5
1  0  0  0  0  0  0  0  0  0  0  0  0
2  4  4  4  4  4  4  4  4  4  4  4  4
3  8  8  8  8  8  8  8  8  8  8  8  8
4  2  2  2  2  2  2  2  2  2  2  2  2

In [0]:
model = RandomForestClassifier(n_estimators=500,)
model.fit(train_df,y_train)
pred1_a_level1=model.predict(df)
train_pred1_a_level1=model.predict(train_df)
model.score(df, y_test)

0.9591269841269842

In [0]:
model = LGBMClassifier(n_estimators=100)
model.fit(train_df,y_train)
model.score(df, y_test)

0.9592857142857143

# **On > 95**

In [0]:
train_df = pd.concat([train_pred1_c,train_pred1_d,train_pred2_c,train_pred2_d,train_pred3_b,train_pred3_e], axis=1)

In [0]:
train_df.head()

0  0  0  0  0  0
0  5  5  5  5  5  5
1  0  0  0  0  0  0
2  4  4  4  4  4  4
3  8  8  8  8  8  8
4  2  2  2  2  2  2

In [0]:
df = pd.concat([pred1_c,pred1_d,pred2_c,pred2_d,pred3_b,pred3_e], axis=1)

In [0]:
df

0  0  0  0  0  0
0      0  0  0  0  0  0
1      8  8  8  8  8  8
2      0  0  0  0  0  0
3      1  1  1  1  1  1
4      7  7  7  7  7  7
...   .. .. .. .. .. ..
12595  7  7  7  7  7  7
12596  1  1  1  1  1  1
12597  0  0  0  0  0  0
12598  6  6  6  6  6  6
12599  7  7  7  7  7  7

[12600 rows x 6 columns]

In [0]:
model = RandomForestClassifier(n_estimators=300)
model.fit(train_df,y_train)
pred1_b_level1=model.predict(df)
train_pred1_b_level1=model.predict(train_df)
model.score(df, y_test)

0.9614285714285714

In [0]:
model = SVC(kernel="rbf",C=25,gamma=0.005)
model.fit(train_df,y_train)
model.score(df, y_test)

0.9597619047619048

In [0]:
model = SVC(kernel="poly",C=20,gamma=0.01)
model.fit(train_df,y_train)
model.score(df, y_test)

0.9592857142857143

In [0]:
model = LGBMClassifier()
model.fit(train_df,y_train)
pred1_c_level1=model.predict(df)
train_pred1_c_level1=model.predict(train_df)
model.score(df, y_test)

0.960952380952381

In [0]:

model = KNeighborsClassifier(n_neighbors=8,weights='distance')
model.fit(train_df,y_train)
model.score(df, y_test)

0.955

# **on > 95.5**

In [0]:
train_df = pd.concat([train_pred1_a,train_pred1_b,train_pred1_c,train_pred1_d,train_pred2_a,train_pred2_b,train_pred2_c,train_pred2_d,train_pred3_b,train_pred3_c,train_pred3_d,train_pred3_e], axis=1)

In [0]:
train_df

0  0  0  0  0  0  0  0  0  0  0  0
0     5  5  5  5  5  5  5  5  5  5  5  5
1     0  0  0  0  0  0  0  0  0  0  0  0
2     4  4  4  4  4  4  4  4  4  4  4  4
3     8  8  8  8  8  8  8  8  8  8  8  8
4     2  2  2  2  2  2  2  2  2  2  2  2
...  .. .. .. .. .. .. .. .. .. .. .. ..
8394  3  3  3  3  3  3  3  3  3  3  3  3
8395  3  3  3  3  3  3  3  3  3  3  3  3
8396  5  3  5  5  5  3  5  5  5  5  5  5
8397  2  2  2  2  2  2  2  2  2  2  2  2
8398  2  2  2  2  2  2  2  2  2  2  2  2

[8399 rows x 12 columns]

In [0]:
df = pd.concat([pred1_a,pred1_b,pred1_c,pred1_d,pred2_a,pred2_b,pred2_c,pred2_d,pred3_b,pred3_c,pred3_d,pred3_e], axis=1)

In [0]:
model = RandomForestClassifier(n_estimators=100,)
model.fit(train_df,y_train)
pred1_d_level1=model.predict(df)
train_pred1_d_level1=model.predict(train_df)
model.score(df, y_test)

0.963015873015873

In [0]:
model = LGBMClassifier( random_state=5,n_estimators=500)
model.fit(train_df,y_train)
model.score(df, y_test)

0.9592857142857143

In [0]:
model = LogisticRegression()
model.fit(train_df,y_train)
p3=model.predict(df)
model.score(df, y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9263492063492064

# **Level 2 Stacking(97.5% highest)**

In [0]:
train_pred1_a_level1=pd.DataFrame(train_pred1_a_level1)
train_pred1_b_level1=pd.DataFrame(train_pred1_b_level1)
train_pred1_c_level1=pd.DataFrame(train_pred1_c_level1)
train_pred1_d_level1=pd.DataFrame(train_pred1_d_level1)

In [0]:
pred1_a_level1=pd.DataFrame(pred1_a_level1)
pred1_b_level1=pd.DataFrame(pred1_b_level1)
pred1_c_level1=pd.DataFrame(pred1_c_level1)
pred1_d_level1=pd.DataFrame(pred1_d_level1)

In [0]:
train_df = pd.concat([train_pred1_a_level1,train_pred1_b_level1,train_pred1_c_level1,train_pred1_d_level1], axis=1)

In [0]:
df = pd.concat([pred1_a_level1,pred1_b_level1,pred1_c_level1,pred1_d_level1], axis=1)

In [0]:
model =LGBMClassifier( random_state=5,n_estimators=100)
model.fit(train_df,y_train)
p1=model.predict(df)
model.score(df, y_test)

0.9755555555555555

In [0]:
model = RandomForestClassifier(n_estimators=500,)
model.fit(train_df,y_train)
p2=model.predict(df)
model.score(df, y_test)

0.975

In [0]:
model = SVC(kernel="rbf",C=10, gamma=0.05)
model.fit(train_df,y_train)
p3=model.predict(df)
model.score(df, y_test)

0.9675396825396826

In [0]:
model = LogisticRegression()
model.fit(train_df,y_train)
p4=model.predict(df)
model.score(df, y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9681746031746031

In [0]:
from statistics import mode
final_pred = np.array([])
for i in range(0,len(X_test)):
  try:
    final_pred = np.append(final_pred, mode([p1[i], p2[i],p3[i],p4[i]]))
  except:
    final_pred = np.append(final_pred,p1[i])

# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=final_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=final_pred))

accuracy: 0.9746825396825397 

[[1204    0    0    0    2    1    7    0    6    1]
 [   0 1357    2    1    4    3    0    3    2    0]
 [   2    3 1227    1    5    2    1    2    5    0]
 [   0    2   14 1287    0   15    0    5    5    2]
 [   1    3    1    3 1185    1    7    2    3   17]
 [   1    2    1   13    0 1115    5    2    1    2]
 [   1    0    2    1    1    8 1215    0    2    0]
 [   2   10   11    4    6    1    0 1322    2   16]
 [   0    7    3    7    1    8    3    3 1189    4]
 [   3    0    1   12   19    3    0   11    6 1180]]
